(function(c){c.jQTouch=function(u){function v(a){h.length<=1&&window.history.go(-2);var b=Math.min(parseInt(a||1,10),h.length-1),d=h[0];if(isNaN(b)&&typeof a==="string"&&a!="#")for(var f=1,e=h.length;f<e;f++)if("#"+h[f].id===a){b=f;break}if(isNaN(b)||b<1)b=1;if(h.length>1){h.splice(0,b);B(d.page,h[0].page,d.animation,d.reverse===false)}else location.hash="#"+d.id;return o}function w(a,b,d){var f=h[0].page;if(typeof b==="string")for(var e=i.length-1;e>=0;e--)if(i[e].name===b){b=i[e];break}if(typeof a===
"string"){nextPage=c(a);if(nextPage.length<1){x(a,{animation:b});return}else a=nextPage}if(B(f,a,b,d)){C(a,b,d);return o}else{console.error("Could not animate pages.");return false}}function D(a){var b=c(a.target);if(b.attr("nodeName")!=="A"&&b.attr("nodeName")!=="AREA")b=b.closest("a, area");a=b.attr("target");var d=b.attr("hash"),f=null;if(y==false||!b.length){console.warn("Not able to tap element.");return false}if(b.isExternalLink()){b.removeClass("active");return true}for(var e=i.length-1;e>=
0;e--)if(b.is(i[e].selector)){f=i[e];break}if(a=="_webapp")window.location=b.attr("href");else if(b.is(g.backSelector))v(d);else if(b.attr("href")=="#"){b.unselect();return true}else if(d&&d!="#"){b.addClass("active");w(c(d).data("referrer",b),f,c(this).hasClass("reverse"))}else{b.addClass("loading active");x(b.attr("href"),{animation:f,callback:function(){b.removeClass("loading");setTimeout(c.fn.unselect,250,b)},$referrer:b})}return false}function C(a,b,d){var f=a.attr("id");h.unshift({page:a,animation:b,
reverse:d||false,id:f})}function B(a,b,d,f){if(b.length===0){c.fn.unselect();console.error("Target element is missing.");return false}if(b.hasClass("current")){c.fn.unselect();console.error("Target element is the current page.");return false}c(":focus").blur();b.css("top",window.pageYOffset);var e=function(){a[0].removeEventListener("webkitTransitionEnd",e);a[0].removeEventListener("webkitAnimationEnd",e);if(d){b.removeClass("start in "+d.name);a.removeClass("start out current "+d.name);if(f){b.toggleClass("reverse");
a.toggleClass("reverse")}b.css("top",0)}else a.removeClass("current");b.trigger("pageAnimationEnd",{direction:"in",reverse:f});a.trigger("pageAnimationEnd",{direction:"out",reverse:f});clearInterval(r);j=b;location.hash="#"+j.attr("id");r=setInterval(E,100);var n=b.data("referrer");n&&n.unselect();z=(new Date).getTime();y=true};a.trigger("pageAnimationStart",{direction:"out"});b.trigger("pageAnimationStart",{direction:"in"});if(c.support.WebKitAnimationEvent&&d&&g.useAnimations){y=false;if(f){b.toggleClass("reverse");
a.toggleClass("reverse")}a[0].addEventListener("webkitTransitionEnd",e);a[0].addEventListener("webkitAnimationEnd",e);b.addClass(d.name+" in current");a.addClass(d.name+" out");setTimeout(function(){b.addClass("start");a.addClass("start")},0)}else{b.addClass("current");e()}return true}function E(){var a=j.attr("id");if(location.hash!="#"+a){clearInterval(r);v(location.hash)}else if(location.hash=="")location.hash="#"+a}function L(a,b){var d=null;c(a).each(function(){var f=c(this);f.attr("id")||f.attr("id",
"page-"+ ++M);k.trigger("pageInserted",{page:f.appendTo(k)});if(f.hasClass("current")||!d)d=f});if(d!==null){w(d,b);return d}else return false}function x(a,b){var d=c.extend({},{data:null,method:"GET",animation:null,callback:null,$referrer:null},b);if(a!="#")c.ajax({url:a,data:d.data,type:d.method,success:function(f){if(f=L(f,d.animation)){d.method=="GET"&&g.cacheGetRequests===true&&d.$referrer&&d.$referrer.attr("href","#"+f.attr("id"));d.callback&&d.callback(true)}},error:function(){d.$referrer&&
d.$referrer.unselect();d.callback&&d.callback(false)}});else d.$referrer&&d.$referrer.unselect()}function F(a,b){var d=typeof a==="string"?c(a).eq(0):a.target?c(a.target):c(a);if(d.length&&d.is(g.formSelector)){x(d.attr("action"),{data:d.serialize(),method:d.attr("method")||"POST",animation:i[0]||null,callback:b});return false}return true}function N(){var a=c(this).closest("form");if(a.length){var b=c.Event("submit");b.preventDefault();a.trigger(b);return false}return true}function G(a){if(typeof a.selector==
"string"&&typeof a.name=="string"){i.push(a);c(a.selector).tap(D);l.push(a.selector)}}function O(){s=Math.abs(window.orientation)==90?"landscape":"portrait";k.removeClass("portrait landscape").addClass(s).trigger("turn",{orientation:s})}function P(a){function b(){f();var q=Math.abs(p),H=Math.abs(t);if(q>H&&q>35&&I<1E3)e.trigger("swipe",{direction:p<0?"left":"right",deltaX:p,deltaY:t}).unbind("touchmove",b).unbind("touchend",d);else H>1&&e.removeClass("active");clearTimeout(A)}function d(){f();if(t===
0&&p===0){e.makeActive();e.trigger("tap")}else e.removeClass("active");e.unbind("touchmove",b).unbind("touchend",d);clearTimeout(A)}function f(){var q=event.changedTouches[0]||null;p=q.pageX-Q;t=q.pageY-R;I=(new Date).getTime()-S}var e=c(a.target);if(!c(a.target).is(l.join(", "))){var n=c(a.target).closest("a, area");if(n.length&&n.is(l.join(", ")))e=n;else return}if(a){var A=null,Q=event.changedTouches[0].clientX,R=event.changedTouches[0].clientY,S=(new Date).getTime(),p=0,t=0,I=0;e.bind("touchmove",
b).bind("touchend",d);A=setTimeout(function(){e.makeActive()},100)}}c.support.WebKitCSSMatrix=typeof WebKitCSSMatrix!="undefined";c.support.touch=typeof TouchEvent!="undefined";c.support.WebKitAnimationEvent=typeof WebKitTransitionEvent!="undefined";var k,T=c("head"),h=[],M=0,g={},r,j,s;/ Mobile\//.test(navigator.userAgent);var y=true,z=0,l=[],o={},J=c.jQTouch.prototype.extensions,K=["slide","flip","slideup","swap","cube","pop","dissolve","fade","back"],i=[],m="";(function(a){g=c.extend({},{addGlossToIcon:true,
backSelector:".back, .cancel, .goback",cacheGetRequests:true,cubeSelector:".cube",dissolveSelector:".dissolve",fadeSelector:".fade",fixedViewport:true,flipSelector:".flip",formSelector:"form",fullScreen:true,fullScreenClass:"fullscreen",icon:null,touchSelector:"a, .touch",popSelector:".pop",preloadImages:false,slideSelector:"#jqt > * > ul li a, .slide",slideupSelector:".slideup",startupScreen:null,statusBar:"default",submitSelector:".submit",swapSelector:".swap",useAnimations:true,useFastTouch:false},
a);if(g.preloadImages)for(a=g.preloadImages.length-1;a>=0;a--)(new Image).src=g.preloadImages[a];if(g.icon)m+='<link rel="apple-touch-icon'+(g.addGlossToIcon?"":"-precomposed")+'" href="'+g.icon+'" />';if(g.startupScreen)m+='<link rel="apple-touch-startup-image" href="'+g.startupScreen+'" />';if(g.fixedViewport)m+='<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;"/>';if(g.fullScreen){m+='<meta name="apple-mobile-web-app-capable" content="yes" />';
if(g.statusBar)m+='<meta name="apple-mobile-web-app-status-bar-style" content="'+g.statusBar+'" />'}m&&T.prepend(m);c(document).ready(function(){for(var b in J){var d=J[b];c.isFunction(d)&&c.extend(o,d(o))}for(b in K){d=K[b];var f=g[d+"Selector"];typeof f=="string"&&G({name:d,selector:f})}l.push("input");l.push(g.touchSelector);l.push(g.backSelector);l.push(g.submitSelector);c(l.join(", ")).css("-webkit-touch-callout","none");c(g.backSelector).tap(D);c(g.submitSelector).tap(N);k=c("#jqt");g.fullScreenClass&&
window.navigator.standalone==true&&k.addClass(g.fullScreenClass+" "+g.statusBar);k.bind("touchstart",P).bind("orientationchange",O).trigger("orientationchange").submit(F);if(g.useFastTouch&&c.support.touch){k.click(function(e){if((new Date).getTime()-z>351){e=c(e.target);if(e.attr("nodeName")!=="A"&&e.attr("nodeName")!=="AREA"&&e.attr("nodeName")!=="INPUT")e=e.closest("a, area");if(e.isExternalLink())return true}return false});k.mousedown(function(){if((new Date).getTime()-z<351)return false})}if(c("#jqt > .current").length==
0)j=c("#jqt > *:first");else{j=c("#jqt > .current:first");c("#jqt > .current").removeClass("current")}c(j).addClass("current");location.hash="#"+c(j).attr("id");C(j);scrollTo(0,0);r=setInterval(E,100)})})(u);c.fn.unselect=function(a){a?a.removeClass("active"):c(".active").removeClass("active")};c.fn.makeActive=function(){return c(this).addClass("active")};c.fn.swipe=function(a){return c.isFunction(a)?c(this).live("swipe",a):c(this).trigger("swipe")};c.fn.tap=function(a){if(c.isFunction(a)){var b=
g.useFastTouch&&c.support.touch?"tap":"click";return c(this).live(b,a)}else return c(this).trigger("tap")};c.fn.isExternalLink=function(){var a=c(this);return a.attr("target")=="_blank"||a.attr("rel")=="external"||a.is('input[type="checkbox"], input[type="radio"], a[href^="http://maps.google.com"], a[href^="mailto:"], a[href^="tel:"], a[href^="javascript:"], a[href*="youtube.com/v"], a[href*="youtube.com/watch"]')};return o={getOrientation:function(){return s},goBack:v,goTo:w,addAnimation:G,submitForm:F}};
c.jQTouch.prototype.extensions=[];c.jQTouch.addExtension=function(u){c.jQTouch.prototype.extensions.push(u)}})(jQuery)